import type { Detection } from "@/data/demoDetections";
import type { SurveyMeta } from "@/data/demoSurvey";

function downloadBlob(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function exportDetectionsCSV(survey: SurveyMeta, detections: Detection[]) {
  const header = [
    "Target ID",
    "Classification",
    "Status",
    "Latitude",
    "Longitude",
    "Depth (m)",
    "Length (m)",
    "Width (m)",
    "Height (m)",
    "Anomaly Score",
    "Confidence",
    "Risk",
  ];
  const rows = detections.map((d) => [
    d.id,
    d.classification,
    d.detectionStatus,
    d.latitude.toFixed(4),
    d.longitude.toFixed(4),
    d.depth.toFixed(1),
    d.length.toFixed(2),
    d.width.toFixed(2),
    d.height.toFixed(2),
    Math.round(d.anomalyScore * 100),
    Math.round(d.confidence * 100),
    d.risk,
  ]);
  const csv = [header, ...rows].map((r) => r.map((v) => `"${v}"`).join(",")).join("\n");
  downloadBlob(csv, `${survey.id}-detections.csv`, "text/csv;charset=utf-8;");
}

function reportHtml(survey: SurveyMeta, topTargets: Detection[]) {
  const rows = topTargets
    .map(
      (d) => `
      <tr>
        <td>${d.id}</td>
        <td>${d.classification}</td>
        <td>${d.latitude.toFixed(4)}, ${d.longitude.toFixed(4)}</td>
        <td>${d.length.toFixed(2)}×${d.width.toFixed(2)}×${d.height.toFixed(2)} m</td>
        <td>${Math.round(d.anomalyScore * 100)}</td>
        <td>${Math.round(d.confidence * 100)}%</td>
      </tr>`
    )
    .join("");

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${survey.id} — Seafloor AI Survey Report</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: Inter, Arial, sans-serif; color: #0a1a2e; padding: 40px; }
  h1 { font-size: 20px; margin-bottom: 2px; letter-spacing: 0.02em; }
  .sub { color: #4c6376; font-size: 12px; margin-bottom: 24px; }
  .meta { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px 24px; margin-bottom: 28px; }
  .meta div span { display: block; }
  .meta .label { font-size: 10px; color: #7d97a8; text-transform: uppercase; letter-spacing: 0.06em; }
  .meta .value { font-size: 14px; font-weight: 600; margin-top: 2px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #dbe4ea; }
  th { color: #4c6376; font-weight: 600; font-size: 10.5px; text-transform: uppercase; letter-spacing: 0.04em; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  <h1>SEAFLOOR AI SURVEY REPORT</h1>
  <div class="sub">Generated by SONARIS — AI-Powered Seafloor Anomaly Detection &amp; Intelligence</div>
  <div class="meta">
    <div><span class="label">Survey</span><span class="value">${survey.id}</span></div>
    <div><span class="label">Area</span><span class="value">${survey.area}</span></div>
    <div><span class="label">Date</span><span class="value">${survey.date}</span></div>
    <div><span class="label">Total Targets</span><span class="value">${survey.totalTargets}</span></div>
    <div><span class="label">Unknown Anomalies</span><span class="value">${survey.unknownAnomalies}</span></div>
    <div><span class="label">High Priority Targets</span><span class="value">${survey.highPriority}</span></div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Target ID</th><th>Classification</th><th>Location</th><th>Size</th><th>Anomaly Score</th><th>Confidence</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
</body>
</html>`;
}

export function exportReportPDF(survey: SurveyMeta, topTargets: Detection[]) {
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(reportHtml(survey, topTargets));
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 300);
}
